module.exports = {
	extends: ['prettier'],
	env: {
		browser: true,
		node: true,
		es2021: true,
	},
	parser: '@typescript-eslint/parser',
	parserOptions: {
		ecmaVersion: 'latest',
		sourceType: 'module',
		extraFileExtensions: ['.svelte', '.svx'],
	},
	plugins: ['svelte3', '@typescript-eslint'],
	settings: {
		'svelte3/typescript': () => require('typescript'),
	},
	reportUnusedDisableDirectives: true,
	ignorePatterns: ['tsconfig.json'],
	rules: {
		// eslint possible problems
		'array-callback-return': 1,
		'for-direction': 1,
		'no-async-promise-executor': 1,
		'no-await-in-loop': 1,
		'no-compare-neg-zero': 1,
		'no-constant-condition': [1, {checkLoops: false}],
		'no-constructor-return': 1,
		'no-control-regex': 1,
		'no-debugger': 1,
		'no-dupe-else-if': 1,
		'no-duplicate-case': 1,
		'no-empty-character-class': 1,
		'no-empty-pattern': 1,
		'no-ex-assign': 1,
		'no-inner-declarations': 1,
		'no-invalid-regexp': 1,
		'no-irregular-whitespace': 1,
		'no-misleading-character-class': 1,
		'no-prototype-builtins': 1,
		'no-self-compare': 1,
		'no-sparse-arrays': 1,
		'no-unmodified-loop-condition': 1,
		'no-unreachable-loop': 1,
		'no-unsafe-finally': 1,
		'no-unsafe-optional-chaining': 1,
		'no-useless-backreference': 1,
		// 'require-atomic-updates': 1, // sometimes very helpful but so many false positives: https://github.com/eslint/eslint/issues/11899
		'use-isnan': 1,
		// eslint suggestions
		'consistent-this': 1,
		'default-case-last': 1,
		'eqeqeq': [1, 'always', {null: 'ignore'}],
		'grouped-accessor-pairs': [1, 'getBeforeSet'],
		'no-alert': 1, // <3 these but often they're for testing; make explicit w/ eslint-ignore-line
		'no-case-declarations': 1,
		'no-constant-binary-expression': 1,
		// 'no-else-return': 1, // a bit too opinionated
		'no-empty': [1, {allowEmptyCatch: true}],
		'no-eval': 1,
		'no-extend-native': 1,
		'no-extra-boolean-cast': 1,
		'no-global-assign': 1,
		'no-lone-blocks': 1,
		'no-multi-str': 1,
		'no-new': 1,
		'no-new-func': 1, // catches cases missed by @typescript-eslint/no-implied-eval
		'no-new-object': 1,
		'no-new-wrappers': 1,
		'no-nonoctal-decimal-escape': 1,
		'no-octal': 1,
		'no-octal-escape': 1,
		'no-param-reassign': 1, // seems better to disallow and ignore when needed; might be annoying
		'no-proto': 1,
		'no-regex-spaces': 1,
		'no-restricted-globals': [1, 'name', 'escape'],
		'no-script-url': 1,
		'no-shadow-restricted-names': 1,
		'no-unneeded-ternary': [1, {defaultAssignment: false}],
		'no-useless-call': 1,
		'no-useless-catch': 1,
		'no-useless-computed-key': [1, {enforceForClassMembers: true}],
		'no-useless-concat': 1,
		'no-useless-escape': 1,
		'no-useless-rename': 1,
		'no-var': 1,
		'no-warning-comments': [1, {terms: ['todo block']}],
		'object-shorthand': 1,
		'operator-assignment': 1,
		'prefer-arrow-callback': 1,
		'prefer-const': 1,
		'prefer-destructuring': [1, {AssignmentExpression: {array: false}}],
		'prefer-exponentiation-operator': 1,
		'prefer-numeric-literals': 1,
		'prefer-object-has-own': 1,
		'prefer-object-spread': 1,
		'prefer-promise-reject-errors': [1, {allowEmptyReject: true}],
		'prefer-regex-literals': [1, {disallowRedundantWrapping: true}],
		'prefer-rest-params': 1,
		'prefer-spread': 1,
		'radix': 1,
		'require-unicode-regexp': 1,
		'require-yield': 1,
		'yoda': 1, // meh
		'no-unused-vars': 1,
	},
	overrides: [
		{
			files: ['*.d.ts'],
			rules: {
				'no-unused-vars': 0,
			}
		},
		{
			files: ['*.ts', '*.svelte', '*.svx'],
			rules: {
				'@typescript-eslint/adjacent-overload-signatures': 1,
				'@typescript-eslint/array-type': [1, {default: 'array-simple', readonly: 'array-simple'}],
				'@typescript-eslint/await-thenable': 1,
				'@typescript-eslint/ban-types': 1,
				'@typescript-eslint/consistent-type-assertions': 1,
				'@typescript-eslint/consistent-type-exports': [
					1,
					{fixMixedExportsWithInlineTypeSpecifier: true},
				],
				'@typescript-eslint/dot-notation': 1,
				'@typescript-eslint/explicit-module-boundary-types': [
					1,
					{allowArgumentsExplicitlyTypedAsAny: true},
				],
				'@typescript-eslint/method-signature-style': 1,
				'@typescript-eslint/no-array-constructor': 1,
				'@typescript-eslint/no-base-to-string': 1,
				'@typescript-eslint/no-duplicate-imports': 1, // TODO deprecated for https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-duplicates.md
				'@typescript-eslint/no-empty-function': 1, // TODO eslint is currently throwing an error with this: `{allow: ['overrideMethods']}`
				'@typescript-eslint/no-empty-interface': 1,
				'@typescript-eslint/no-extra-non-null-assertion': 1,
				'@typescript-eslint/no-duplicate-enum-values': 1,
				'@typescript-eslint/no-floating-promises': [1, {ignoreIIFE: true}],
				'@typescript-eslint/no-for-in-array': 1,
				'@typescript-eslint/no-implied-eval': 1,
				'@typescript-eslint/no-inferrable-types': 1,
				'@typescript-eslint/no-invalid-this': [1, {capIsConstructor: false}],
				// '@typescript-eslint/no-invalid-void-type': [1, {allowAsThisParameter: true}], // helpful but too many false positives
				'@typescript-eslint/no-loss-of-precision': 1,
				'@typescript-eslint/no-meaningless-void-operator': 1,
				'@typescript-eslint/no-misused-new': 1,
				'@typescript-eslint/no-misused-promises': [1, {checksVoidReturn: false}],
				'@typescript-eslint/no-namespace': 1,
				'@typescript-eslint/no-non-null-asserted-nullish-coalescing': 1,
				'@typescript-eslint/no-non-null-asserted-optional-chain': 1,
				'@typescript-eslint/no-require-imports': 1,
				'@typescript-eslint/no-this-alias': 1,
				'@typescript-eslint/no-throw-literal': 1,
				'@typescript-eslint/no-unnecessary-boolean-literal-compare': 1,
				// TODO is erroring with eslint@8.20.0 and @typescript-eslint/eslint-plugin@5.30.7 -- Cannot read properties of undefined (reading 'kind')
				// '@typescript-eslint/no-unnecessary-type-assertion': 1,
				'@typescript-eslint/no-unnecessary-type-constraint': 1,
				'@typescript-eslint/no-unused-expressions': [
					1,
					{allowShortCircuit: true, allowTernary: true, allowTaggedTemplates: true},
				],
				'@typescript-eslint/no-useless-constructor': 1,
				'@typescript-eslint/non-nullable-type-assertion-style': 1,
				'@typescript-eslint/prefer-as-const': 1,
				'@typescript-eslint/prefer-for-of': 1,
				'@typescript-eslint/prefer-includes': 1,
				'@typescript-eslint/prefer-namespace-keyword': 1,
				'@typescript-eslint/prefer-optional-chain': 1,
				'@typescript-eslint/prefer-regexp-exec': 1,
				'@typescript-eslint/prefer-string-starts-ends-with': 1,
				'@typescript-eslint/prefer-ts-expect-error': 1,
				'@typescript-eslint/no-redundant-type-constituents': 1,
				'@typescript-eslint/require-array-sort-compare': [1, {ignoreStringArrays: true}],
				'@typescript-eslint/return-await': 1,
				'@typescript-eslint/switch-exhaustiveness-check': 1,
				'@typescript-eslint/triple-slash-reference': [
					1,
					{path: 'never', types: 'never', lib: 'never'},
				],
			},
		},
		{
			files: ['*.svelte', '*.svx'],
			processor: 'svelte3/svelte3',
			rules: {
				'@typescript-eslint/no-unused-expressions': 0, // allow Svelte idioms like `$: someVar, doSomething()`
			},
		},
		{
			files: ['*.js', '*.cjs'],
			parser: 'espree',
		}
	],
};