services:

  browserless:
    image: ghcr.io/browserless/chrome:latest
    environment:
      CONCURRENT: 10
      TOKEN: null
    network_mode: host
    restart: always

  umami:
    image: docker.umami.is/umami-software/umami:latest
    ports:
      - 8079:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/umami
    networks:
      - yapms
    restart: always

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_PASSWORD: password
    networks:
      - yapms
    restart: always

networks:
  yapms:
