#!/bin/bash
cd $(dirname "$0")
cd ./app/src/
cat Account.js Candidate.js ChartManager.js CookieManager.js InputManager.js KeyboardManager.js LegendManager.js LogoManager.js MapManager.js MapLoader.js PresetLoader.js State.js battlechart.js click.js congress.js data.js SimulatorData.js htmlControl.js Simulator.js SaveMap.js Tools.js main.js > ../bin/yapms.js
cd ../style/
cat mysaves.css input.css menu.css selectmenu.css popup.css legend.css style.css battlechart.css yapnews.css sidebar.css consent.css > ../bin/yapms.css
cd $(dirname "$0")
