FROM golang:1.21 AS INSTALLER
WORKDIR /app
COPY apps/pocketbase/ .
RUN go clean
RUN go get github.com/pocketbase/pocketbase
RUN go build
RUN ./pocketbase migrate

FROM golang:1.21 AS RUNNER
WORKDIR /app
COPY --from=INSTALLER /app/pocketbase .
COPY --from=INSTALLER /app/pb_data ./pb_data
CMD ./pocketbase serve --http=0.0.0.0:8080