FROM golang:1.22-alpine AS INSTALLER
WORKDIR /app
COPY apps/pocketbase/ .
RUN go clean
RUN go build
RUN ./pocketbase migrate

FROM golang:1.22-alpine AS RUNNER
WORKDIR /app
RUN apk add pngquant
COPY --from=INSTALLER /app/pocketbase .
COPY --from=INSTALLER /app/pb_data ./pb_data
CMD ./pocketbase serve --http=0.0.0.0:8080
